INSERT INTO usuario (nome, email, senha, role) VALUES
                                                   ('Administrador', 'admin@systrack.com', '$2a$12$Zz.rN7AlI9n6UsdGgUwgxuopxQzt7JNfwi0zWVWREe9.vx6Gt8ntW', 'ADMIN'),
                                                   ('Usuário Padrão', 'user@systrack.com', '$2a$12$Zz.rN7AlI9n6UsdGgUwgxuopxQzt7JNfwi0zWVWREe9.vx6Gt8ntW', 'USER'),
                                                   ('Usuário 1', 'user1@systrack.com', '$2a$12$Zz.rN7AlI9n6UsdGgUwgxuopxQzt7JNfwi0zWVWREe9.vx6Gt8ntW', 'USER'),
                                                   ('Usuário 2', 'user2@systrack.com', '$2a$12$Zz.rN7AlI9n6UsdGgUwgxuopxQzt7JNfwi0zWVWREe9.vx6Gt8ntW', 'USER'),
                                                   ('Usuário 3', 'user3@systrack.com', '$2a$12$Zz.rN7AlI9n6UsdGgUwgxuopxQzt7JNfwi0zWVWREe9.vx6Gt8ntW', 'USER'),
                                                   ('Usuário 4', 'user4@systrack.com', '$2a$12$Zz.rN7AlI9n6UsdGgUwgxuopxQzt7JNfwi0zWVWREe9.vx6Gt8ntW', 'USER'),
                                                   ('Usuário 5', 'user5@systrack.com', '$2a$12$Zz.rN7AlI9n6UsdGgUwgxuopxQzt7JNfwi0zWVWREe9.vx6Gt8ntW', 'USER'),
                                                   ('Usuário 6', 'user6@systrack.com', '$2a$12$Zz.rN7AlI9n6UsdGgUwgxuopxQzt7JNfwi0zWVWREe9.vx6Gt8ntW', 'USER'),
                                                   ('Usuário 7', 'user7@systrack.com', '$2a$12$Zz.rN7AlI9n6UsdGgUwgxuopxQzt7JNfwi0zWVWREe9.vx6Gt8ntW', 'USER'),
                                                   ('Usuário 8', 'user8@systrack.com', '$2a$12$Zz.rN7AlI9n6UsdGgUwgxuopxQzt7JNfwi0zWVWREe9.vx6Gt8ntW', 'USER'),
                                                   ('Usuário 9', 'user9@systrack.com', '$2a$12$Zz.rN7AlI9n6UsdGgUwgxuopxQzt7JNfwi0zWVWREe9.vx6Gt8ntW', 'USER'),
                                                   ('Usuário 10', 'user10@systrack.com', '$2a$12$Zz.rN7AlI9n6UsdGgUwgxuopxQzt7JNfwi0zWVWREe9.vx6Gt8ntW', 'USER'),
                                                   ('Usuário 11', 'user11@systrack.com', '$2a$12$Zz.rN7AlI9n6UsdGgUwgxuopxQzt7JNfwi0zWVWREe9.vx6Gt8ntW', 'USER'),
                                                   ('Usuário 12', 'user12@systrack.com', '$2a$12$Zz.rN7AlI9n6UsdGgUwgxuopxQzt7JNfwi0zWVWREe9.vx6Gt8ntW', 'USER'),
                                                   ('Usuário 13', 'user13@systrack.com', '$2a$12$Zz.rN7AlI9n6UsdGgUwgxuopxQzt7JNfwi0zWVWREe9.vx6Gt8ntW', 'USER'),
                                                   ('Usuário 14', 'user14@systrack.com', '$2a$12$Zz.rN7AlI9n6UsdGgUwgxuopxQzt7JNfwi0zWVWREe9.vx6Gt8ntW', 'USER'),
                                                   ('Usuário 15', 'user15@systrack.com', '$2a$12$Zz.rN7AlI9n6UsdGgUwgxuopxQzt7JNfwi0zWVWREe9.vx6Gt8ntW', 'USER'),
                                                   ('Usuário 16', 'user16@systrack.com', '$2a$12$Zz.rN7AlI9n6UsdGgUwgxuopxQzt7JNfwi0zWVWREe9.vx6Gt8ntW', 'USER'),
                                                   ('Usuário 17', 'user17@systrack.com', '$2a$12$Zz.rN7AlI9n6UsdGgUwgxuopxQzt7JNfwi0zWVWREe9.vx6Gt8ntW', 'USER'),
                                                   ('Usuário 18', 'user18@systrack.com', '$2a$12$Zz.rN7AlI9n6UsdGgUwgxuopxQzt7JNfwi0zWVWREe9.vx6Gt8ntW', 'USER');
